MVCAccessDB/Controllers/MDTUserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCAccessDB.Models;
using System.Data;
using System.Data.OleDb;
using System.Configuration;

namespace MVCAccessDB.Controllers
{
    public class MDTUserController : Controller
    {
        // GET: MDTUser
        public ActionResult Index()
        {
            try
            {
                HttpCookie myCookie = Request.Cookies["MDTuserCookie"];

                if (myCookie == null || myCookie["userid"] == null )
                    return RedirectToAction("index", "Home");

                IList<PatientModel> patients = new List<PatientModel>();
                OleDbConnection myConnection = new OleDbConnection();

                myConnection.ConnectionString = ConfigurationManager.AppSettings["ConnectionString"];
                // OleDbConnection myConnection = new OleDbConnection("Provider=Microsoft.ACE.OLEDB.12.0;Data Source=c:\\users\\anshi\\documents\\mdtaccessdb.accdb");

                myConnection.Open();

                //var datT = myConnection.GetSchema("user");
                OleDbCommand cmd = new OleDbCommand("Select * FROM [Patient] where Deleted = false", myConnection);
                OleDbDataAdapter adapter;
                adapter = new OleDbDataAdapter(cmd);

                DataSet ds = new DataSet("MainDataSet");

                adapter.Fill(ds);

                var patientList = ds.Tables[0];
                foreach (DataRow patient in patientList.Rows)
                {
                    // MDTDetails mDTDetails = new MDTDetails();
                    IList<MDTDetails> mDTDetails = new List<MDTDetails>();
                    //var MdtDetails = db.MdtEpisodes.Where(x => x.MdtPatientId == patient.PatientId).OrderByDescending(x => x.MdtDate).ToList();
                    //if (MdtDetails != null)
                    //    foreach (var mdt in MdtDetails)
                    //        mDTDetails.Add(new MDTDetails { MDTId = mdt.MdtId, MDTDate = mdt.MdtDate });

                    patients.Add(new PatientModel
                    {
                        FirstName = patient["FirstName"].ToString(),
                        LastName = patient["LastName"].ToString(),
                        NhsNo = patient["NhsNo"].ToString(),
                        HospitalNo = patient["HospitalNo"].ToString(),
                        PatientId = Convert.ToInt32(patient["PatientId"].ToString()),
                        //MDTEpisode = mDTDetails
                    });
                }
                myConnection.Close();
                return View(patients);
            }
            catch
            {
                return View("Error");
                /// return view
            }
        }

        public ActionResult Details(int? id = 0) //Patient Id
        {
            try
            {
                HttpCookie myCookie = Request.Cookies["MDTuserCookie"];

                if (myCookie == null || myCookie["userid"] == null )
                    return RedirectToAction("index", "Home");
          
            MDTModel model = new MDTModel();
            if (id != null && id > 0)
            {
                OleDbDataAdapter adapter;
                OleDbConnection myConnection = new OleDbConnection();
                myConnection.ConnectionString = ConfigurationManager.AppSettings["ConnectionString"];

                myConnection.Open();

                OleDbCommand cmd = new OleDbCommand("Select * FROM [MDT] where MDTPatientId = " + id + " order by MDTDate Desc", myConnection);
                adapter = new OleDbDataAdapter(cmd);
                DataSet ds = new DataSet("MainDataSet");

                adapter.Fill(ds);
                //  IList<MDTModel> mdts = new List<MDTModel>();
                if (ds.Tables.Count > 0)
                {
                    var mdtlist = ds.Tables[0];
                    // var userList = db.Users.ToList();
                    foreach (DataRow mdt in mdtlist.Rows)
                    {
                        model.Comorbidities = mdt["Comorbidities"].ToString();
                        model.History = mdt["History"].ToString();
                        model.MDTDate = Convert.ToDateTime(mdt["MdtDate"].ToString());
                        model.MDTDiscussion = mdt["MdtDiscussion"].ToString();
                        model.MdtId = Convert.ToInt32(mdt["MdtId"].ToString());
                        model.MDTPatientId = Convert.ToInt32(mdt["MDTPatientId"].ToString());
                        // users.Add(new UserModel
                        break;
                    }


                    cmd = new OleDbCommand("Select * FROM [Patient] where PatientId = " + id, myConnection);
                    adapter = new OleDbDataAdapter(cmd);
                    ds = new DataSet("MainDataSet");
                    adapter.Fill(ds);
                    if (ds.Tables.Count > 0)
                    {
                        var patientlist = ds.Tables[0];
                        // var userList = db.Users.ToList();
                        foreach (DataRow patient in patientlist.Rows)
                        {
                            model.Patient.FirstName = patient["FirstName"].ToString();
                            model.Patient.LastName = patient["LastName"].ToString();
                            model.Patient.NhsNo = patient["NhsNo"].ToString();
                            model.Patient.PatientId = Convert.ToInt32(patient["PatientId"].ToString());
                            model.Patient.AddressLine1 = patient["AddressLine1"].ToString();
                            model.Patient.AddressLine2 = patient["AddressLine2"].ToString();
                            model.Patient.City = patient["City"].ToString();
                            model.Patient.DateofBirth = Convert.ToDateTime(patient["DateofBirth"].ToString());
                            model.Patient.GpAddressLine1 = patient["GpAddressLine1"].ToString();
                            model.Patient.GpAddressLine2 = patient["GpAddressLine2"].ToString();
                            model.Patient.GpCity = patient["GpCity"].ToString();
                            model.Patient.GpName = patient["GpName"].ToString();
                            model.Patient.GpPostcode = patient["GpPostcode"].ToString();
                            model.Patient.HospitalNo = patient["HospitalNo"].ToString();
                            model.Patient.Postcode = patient["Postcode"].ToString();
                        }
                    }
                }

                cmd = new OleDbCommand("Select * FROM [MDTUser] where MDTId = " + model.MdtId, myConnection);
                adapter = new OleDbDataAdapter(cmd);
                ds = new DataSet("MainDataSet");
                adapter.Fill(ds);
                if (ds.Tables.Count > 0)
                {
                    var userlist = ds.Tables[0];
                    // var userList = db.Users.ToList();
                    foreach (DataRow userdetail in userlist.Rows)
                    {
                        model.Users.Add(new UserList { UserId = Convert.ToInt32(userdetail["UserId"].ToString()), FullName = userdetail["FullName"].ToString(), Selected = true });
                    }
                }

                cmd = new OleDbCommand("Select * FROM [MDT] where MDTPatientId = " + model.MDTPatientId + " order by MDTDate desc", myConnection);

                adapter = new OleDbDataAdapter(cmd);

                ds = new DataSet("MainDataSet");

                adapter.Fill(ds);
                if (ds.Tables.Count > 0)
                {
                    var mdtList = ds.Tables[0];
                    foreach (DataRow mdtdetail in mdtList.Rows)
                    {

                        model.MDTEpisode.Add(new MDTDetails { MDTId = Convert.ToInt32(mdtdetail["MdtId"].ToString()), MDTDate = Convert.ToDateTime(mdtdetail["MdtDate"].ToString()) });
                    }
                }
                myConnection.Close();
                
                return View(model);
            }
            return View(model);
            }
            catch { return View("Error"); }
        }

        public ActionResult MDTDetails(int? id = 0) //MDT Id
        {
            try
            {
                HttpCookie myCookie = Request.Cookies["MDTuserCookie"];

                if (myCookie == null || myCookie["userid"] == null )
                    return RedirectToAction("index", "Home");
                MDTModel model = new MDTModel();
            if (id != null && id > 0)
            {
                OleDbDataAdapter adapter;
                OleDbConnection myConnection = new OleDbConnection();
                myConnection.ConnectionString = ConfigurationManager.AppSettings["ConnectionString"];

                myConnection.Open();

                OleDbCommand cmd = new OleDbCommand("Select * FROM [MDT] where MDTId = " + id, myConnection);
                
                adapter = new OleDbDataAdapter(cmd);
                DataSet ds = new DataSet("MainDataSet");

                adapter.Fill(ds);
                //  IList<MDTModel> mdts = new List<MDTModel>();
                if (ds.Tables.Count > 0)
                {
                    var mdtlist = ds.Tables[0];
                    // var userList = db.Users.ToList();
                    foreach (DataRow mdt in mdtlist.Rows)
                    {
                        model.Comorbidities = mdt["Comorbidities"].ToString();
                        model.History = mdt["History"].ToString();
                        model.MDTDate = Convert.ToDateTime(mdt["MdtDate"].ToString());
                        model.MDTDiscussion = mdt["MdtDiscussion"].ToString();
                        model.MdtId = Convert.ToInt32(mdt["MdtId"].ToString());
                        model.MDTPatientId = Convert.ToInt32(mdt["MDTPatientId"].ToString());
                        // users.Add(new UserModel

MVCAccessDB/Views/MDTUser/Details.cshtml
@model MVCAccessDB.Models.MDTModel
@{
    ViewBag.Title = "Patient Details";
}
<!-- jQuery UI CSS Reference -->
<!-- Required jQuery and jQuery UI Javascript references -->
@*<link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-ui-1.12.1.js"></script>
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>*@
@*<div class="container">*@
<div class="row">
    <div class="col-md-2" style="margin-top:20px">
        <div class="vertical-menu">
            <a href="#" class="active">Main Menu</a>
            @Html.ActionLink("Patients", "Index", "MDTUser")
            @Html.ActionLink("Logout", "Index", "Home")
        </div>

        <div class="vertical-menu" style="margin-top:20px">
            <a href="#" class="active">Episode Menu</a>
            @*@Html.ActionLink("View all episodes", "Index", "Patient")*@
            @if (Model.MDTEpisode != null && Model.MDTEpisode.Count > 0)
            {
                foreach (var mdt in Model.MDTEpisode)
                {

                    @Html.ActionLink("Episode " + mdt.MDTDate.ToShortDateString(), "Details", "MDT", new { id = mdt.MDTId }, null)

                }

            }
        </div>

        <div class="vertical-menu" style="margin-top:20px">
            <a href="#" class="active">Attendees  @DateTime.Now.ToShortDateString()</a>
            <input type="checkbox" name="user" value="1" style="padding-left:10px">Vivek Srivastava<br>
            <input type="checkbox" name="user" value="2" style="padding-left:10px">Shakil

        </div>
    </div>
    <div class="col-md-10" style="text-align: left;">
        <h3 style="color:#003366">@Model.Patient.FirstName @Model.Patient.LastName</h3>
        <div class="card">
            <div class="header">
                <div class="row">
                    <div class="col-md-4"><div class="col-md-6"><b>Hospital No: </b></div><div class="col-md-6">@Model.Patient.HospitalNo</div></div>
                    <div class="col-md-4"><div class="col-md-6"><b>Date Of Birth: </b></div><div class="col-md-6">@Model.Patient.DateofBirth.ToShortDateString()</div></div>
                    <div class="col-md-4"><div class="col-md-6"><b>GP Name: </b></div><div class="col-md-6">@Model.Patient.GpName</div></div>
                </div>
                <div class="row" style="padding-top:10px">
                    <div class="col-md-4"><div class="col-md-6"><b>NHS No: </b></div><div class="col-md-6">@Model.Patient.NhsNo</div></div>
                    <div class="col-md-4"><div class="col-md-6"><b>Address: </b></div><div class="col-md-6">@Model.Patient.AddressLine1</div></div>
                    <div class="col-md-4"><div class="col-md-6"><b>GP Address: </b></div><div class="col-md-6">@Model.Patient.GpAddressLine1</div></div>
                </div>
                <div class="row" style="padding-top:10px">
                    <div class="col-md-4"><div class="col-md-6"><b>First Name: </b></div><div class="col-md-6">@Model.Patient.FirstName</div></div>
                    <div class="col-md-4"><div class="col-md-6"><b> </b></div><div class="col-md-6">@Model.Patient.AddressLine2 @Model.Patient.City</div></div>
                    <div class="col-md-4"><div class="col-md-6"><b></b></div><div class="col-md-6">@Model.Patient.GpAddressLine2 @Model.Patient.GpCity</div></div>
                </div>
                <div class="row" style="padding-top:10px">
                    <div class="col-md-4"><div class="col-md-6"><b>Surname: </b></div><div class="col-md-6">@Model.Patient.LastName</div></div>
                    <div class="col-md-4"><div class="col-md-6"><b>Postcode: </b></div><div class="col-md-6">@Model.Patient.Postcode</div></div>
                    <div class="col-md-4"><div class="col-md-6"><b>Postcode: </b></div><div class="col-md-6">@Model.Patient.GpPostcode</div></div>
                </div>
            </div>
        </div>
        @*<div class="container" style="margin-top:20px;padding:15px">*@
        @*<div class="row">
                <div class="col-md-4"><div class="col-md-6"><b>Hospital No: </b></div><div class="col-md-6">@Model.Patient.HospitalNo</div></div>
                <div class="col-md-4"><div class="col-md-6"><b>Date Of Birth: </b></div><div class="col-md-6">@Model.Patient.DateofBirth.ToShortDateString()</div></div>
                <div class="col-md-4"><div class="col-md-6"><b>GP Name: </b></div><div class="col-md-6">@Model.Patient.GpName</div></div>
            </div>
            <div class="row">
                <div class="col-md-4"><div class="col-md-6"><b>NHS No: </b></div><div class="col-md-6">@Model.Patient.NhsNo</div></div>
                <div class="col-md-4"><div class="col-md-6"><b>Address: </b></div><div class="col-md-6">@Model.Patient.AddressLine1</div></div>
                <div class="col-md-4"><div class="col-md-6"><b>GP Address: </b></div><div class="col-md-6">@Model.Patient.GpAddressLine1</div></div>

            </div>
            <div class="row">
                <div class="col-md-4"><div class="col-md-6"><b>First Name: </b></div><div class="col-md-6">@Model.Patient.FirstName</div></div>
                <div class="col-md-4"><div class="col-md-6"><b> </b></div><div class="col-md-6">@Model.Patient.AddressLine2 @Model.Patient.City</div></div>
                <div class="col-md-4"><div class="col-md-6"><b></b></div><div class="col-md-6">@Model.Patient.GpAddressLine2 @Model.Patient.GpAddressLine2</div></div>
            </div>
            <div class="row">
                <div class="col-md-4"><div class="col-md-6"><b>Surname: </b></div><div class="col-md-6">@Model.Patient.LastName</div></div>
                <div class="col-md-4"><div class="col-md-6"><b>Postcode: </b></div><div class="col-md-6">@Model.Patient.Postcode</div></div>
                <div class="col-md-4"><div class="col-md-6"><b>Postcode: </b></div><div class="col-md-6">@Model.Patient.GpPostcode</div></div>
            </div>*@
        @*</div>*@
        @*@Html.ActionLink("Add Episode", "Create", "MDT", new { id = Model.Patient.PatientId }, null)
            <button class="btn btn-primary pull-left" style="background-color:#003366" onclick="location.href='@Url.Action("Create", "MDT" , new { id = Model.Patient.PatientId })'">Add New Episode</button>*@
        <div style="margin-top:20px;margin-bottom:10px">
            <h3 style="color:#003366">Episode  @Model.MDTDate.ToShortDateString() </h3>
        </div>
        @*<div class="container" style="padding:15px;">*@
        <div class="row" style="padding-top:10px">
            <div class="col-md-6"><div class="col-md-6"><b>MDT Date: </b></div><div class="col-md-6">@Model.MDTDate.ToShortDateString()</div></div>
            <div class="col-md-6"><div class="col-md-6"><b>Other: </b></div><div></div></div>
        </div>
        <div class="row" style="padding-top:10px">
            <div class="col-md-6"><div class="col-md-6"><b>History: </b></div><div class="col-md-6">@Model.History</div></div>
            <div class="col-md-6"><div class="col-md-6"><b>Other: </b></div><div class="col-md-6"></div></div>

        </div>
        <div class="row" style="padding-top:10px">
            <div class="col-md-6"><div class="col-md-6"><b>MDT Discussion: </b></div><div class="col-md-6">@Model.MDTDiscussion</div></div>
            <div class="col-md-6"><div class="col-md-6"><b>Other: </b></div><div class="col-md-6"></div></div>
        </div>
        <div class="row" style="padding-top:10px">
            <div class="col-md-6"><div class="col-md-6"><b>Comorbidities: </b></div><div class="col-md-6">@Model.Comorbidities</div></div>
            <div class="col-md-6"><div class="col-md-6"><b>Other: </b></div><div class="col-md-6"></div></div>
        </div>
    </div>
    @*</div>*@
</div>
@*</div>*@

MVCAccessDB/Views/MDTUser/Index.cshtml
@model IEnumerable<MVCAccessDB.Models.PatientModel>
@{
    ViewBag.Title = "Patients";
}
<div class="row">
    <div class="col-md-2" style="margin-top:20px">
        <div class="vertical-menu">
            <a href="#" class="active">Main Menu</a>
            @Html.ActionLink("Patients", "Index", "MDTUser")
            @Html.ActionLink("Logout", "Index", "Home")
        </div>
    </div>
    <div class="col-md-10" style="text-align: left;">
        <h3 style="color:#003366">Patients</h3>
        @using (@Html.BeginForm("Filter", "Patient"))
        {

            <div class="container">
                <div class="row">
                    <div id="filter-panel" class="filter-panel">
                        <div class="panel panel-default">
                            <div class="panel-body">
                                <div>
                                    <div class="col-sm-3">
                                        @Html.TextBox("txtFilter", "", new { placeholder = "Name, NHS No, Hospital No", @class = "form-control input-sm" })
                                    </div>
                                    @*<div class="col-sm-3">
                                            @*<label class="filter-col" style="margin-right: 0;" for="pref-search">Location:</label>
                                            @Html.DropDownListFor(x => x.CategoryId, Model.CategoryList, "Select a location", new { @class = "form-control input-sm " })
                                        </div>
                                        <div class="col-sm-3">

                                            @Html.DropDownListFor(x => x.CategoryId, Model.CategoryList, "Select a category", new { @class = "form-control input-sm" })
                                        </div>*@
                                    <div class="col-sm-3">
                                        <input style="text-align: left; background-color:#003366" class="btn btn-primary pull-left" type="submit" value="Search" />
                                    </div>
                                </div>
                                @*///form*@
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }
       
        <table class="table" style="padding-top:20px">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.FirstName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.LastName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.NhsNo)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.HospitalNo)
                </th>
              
                <th>
                   
                </th>
                               
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.FirstName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.LastName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NhsNo)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.HospitalNo)
                    </td>
                  
                    <td>
                       
                        @Html.ActionLink("View MDT", "Details", new { id = item.PatientId }) 
                      
                    </td>
                </tr>
            }
        </table>
        <div></div>
    </div>
</div>